title= "STAP-Zoo"

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

disableKinds = ["RSS"]

[params.ui]
navbar_logo = false

[params.footer]
copyright = "© 2026 **STAP-Zoo**. All Rights Reserved. Built with AI assistance."

[params.katex]
enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]


